#!/bin/sh
#
# IsoBuilder for TinyCore64
#
# alphons@heijden.com
#
#
ISOBUILDER="2023-02-03 v1.12"
#
# WORKINGDIR must have write rights for executing user (not root)
#
WORKINGDIR="/mnt/sda1"
RELEASE="release"
ISOSRC="CorePure64-14.a.iso"
NEWISO="new-CorePure64-14.a.iso"
KERNELVERSION="6.1.9"
#
# ---------------------------------------------------------
#
REMOTE="http://www.tinycorelinux.net/13.x/x86_64/release/"
ISODIR="$WORKINGDIR/$RELEASE"
#
LINUX="linux-$KERNELVERSION"
LINSRC="https://cdn.kernel.org/pub/linux/kernel/v6.x/$LINUX.tar.xz"
LINUXPATH="$WORKINGDIR/$LINUX"
#
LIBNAME="$KERNELVERSION-tinycore64"
#
# GLIB is experimental at the moment
GLIBVERSION="glibc-2.36"
#
KERNEL=vmlinuz64
INITRD=$ISODIR/initrd
BOOT=$ISODIR/iso_contents/boot
#
SCRIPTDIR=$PWD
#
echo "checking packages"
tce-load -wi rsync mkisofs-tools >/dev/null
tce-load -wi coreutils compiletc gcc binutils make squashfs-tools ncursesw-dev bison >/dev/null
tce-load -wi flex-dev openssl-1.1.1-dev elfutils-dev gettext-dev bc perl5 python3.9 texinfo >/dev/null
#
#
function IsoExtract () 
{
  echo
  echo "Unpacking ISO to iso_contents and initrd"  
  cd $ISODIR
  if [ -d "iso_contents" ] && [ -d "initrd" ]; then
    echo "Removing old iso_contents and initrd"
    sudo rm -rf iso_contents
    sudo rm -rf initrd
  fi 

  echo "making iso_contents"
  sudo mkdir iso_contents_org
  sudo mkdir iso_contents
  sudo mount -o loop $ISOSRC iso_contents_org
  sudo rsync -a -H iso_contents_org/ iso_contents/
  sudo umount iso_contents_org
  sudo rm -rf iso_contents_org
  MakeInitRd $ISODIR/iso_contents/boot
}

function MakeInitRd()
{
  CONTENTSBOOT=$1
  echo "making initrd"
  sudo mkdir initrd
  cd initrd
  if [[ -f $CONTENTSBOOT/corepure64.gz ]]; then
    echo "gunzip corepure64.gz"
    sudo gunzip -c $CONTENTSBOOT/corepure64.gz | sudo cpio -id -H newc
  fi
  if [[ -f $CONTENTSBOOT/rootfs64.gz ]]; then
    echo "gunzip rootfs64.gz"
    sudo gunzip -c $CONTENTSBOOT/rootfs64.gz | sudo cpio -id -H newc
  fi
  if [[ -f $CONTENTSBOOT/modules64.gz ]]; then
    echo "gunzip modules64.gz"
    sudo gunzip -c $CONTENTSBOOT/modules64.gz | sudo cpio -id -H newc
  fi
  echo "Done"
}

function Install () 
{
  echo
  cd $LINUXPATH
  echo "Install kernel and modules"

  LIB=$INITRD/lib/modules/$LIBNAME

  if [ -d "$INITRD" ]; then

    echo "0 Remove old tinycore64 modules directory"
    sudo rm -rf $INITRD/lib/modules/*-tinycore64

    echo "1 Creating LIB directory"  
    sudo mkdir -p $LIB

    echo "2 Installing modules in $LIB (takes a while)"
    sudo make INSTALL_MOD_PATH=$INITRD modules_install >/dev/null
  
    echo "3 Compressing modules in LIB directory"
    sudo find $LIB -name '*.ko' -exec gzip -9 {} \;

    sudo rm -rf $LIB/build
    sudo rm -rf $LIB/source
  
    echo "4 Depmodding the new gzipped modules"
    sudo depmod -b $INITRD $LIBNAME
  
    echo "5 Linking tinycore usr/local/lib new version kernel.tclocal"
    sudo ln -s /usr/local/lib/modules/$LIBNAME/ $LIB/kernel.tclocal

    TOTAL=`find $LIB -name '*.ko.gz' | wc -l`
    echo "6 Modules (total $TOTAL) are ready in $LIB"

    echo "7 Making tree from $LIBNAME in $RELEASE"
    tree -h $ISODIR/initrd/lib/modules/$LIBNAME/kernel > $ISODIR/tree.txt

    echo "8 removing old kernel"  
    sudo rm $BOOT/$KERNEL

    echo "9 copying new kernel as $KERNEL and make it readonly"
    sudo cp ./arch/x86/boot/bzImage $BOOT/$KERNEL
  
    sudo chmod 444 $BOOT/$KERNEL
    echo
    echo "New kernel and modules are ready to pack in an ISO"
  else
    echo "initrd directory does not exist: $INITRD"
  fi
}

function MakeISOFS()
{
  echo
  echo "Make ISO FS"
  cd $ISODIR
  if [[ -d "iso_contents" ]]; then
    echo "Creating ISO from only iso_contents (no initrd)"
    cd iso_contents

    cd boot
    
    if [ -f corepure64.gz ]; then
      echo "initrd points to corepure64.gz"
      sudo sed -i 's/\tinitrd.*/\tinitrd \/boot\/corepure64.gz/g' isolinux/isolinux.cfg
    fi
    
    if [ -f rootfs64.gz ] && [ -f modules64.gz ]; then
      echo "initrd points to rootfs64.gz and modules64.gz"
      sudo sed -i 's/\tinitrd.*/\tinitrd \/boot\/rootfs64.gz,\/boot\/modules64.gz/g' isolinux/isolinux.cfg
    fi
    cd ..
    sudo mkisofs -r -R -l -J \
      -no-emul-boot \
      -V TC-custom \
      -boot-load-size 4 \
      -boot-info-table \
      -b boot/isolinux/isolinux.bin \
      -c boot/isolinux/boot.cat \
      -quiet -o ../$NEWISO \
      ./
    cd ..
    sudo chown tc:staff $NEWISO
    FILESIZE=$(stat -c%s "$NEWISO")
    echo "Done creating $NEWISO size $FILESIZE"
  else
    echo "iso_contents does not exist, try ISO extract first"
  fi
} 


function MakeNewIso ()
{
  echo "Making new ISO from iso_contents and initrd"
  cd $ISODIR
  if [ -d "iso_contents" ] && [ -d "initrd" ]; then
    echo "renoving old gz files form iso_contents/boot"
    sudo rm -rf ./iso_contents/boot/*.gz
    echo "Creating corepure64.gz from initrd"
    cd initrd
    sudo sh -c 'find . | cpio --create --format='newc' | gzip -6f > ../iso_contents/boot/corepure64.gz'
    MakeISOFS
  else
    echo "iso_contents or initrd does not exist, try ISO extract first"
  fi
}

function PurgeExtraction ()
{
  echo
  echo "Purge extraction"
  cd $ISODIR

  if [ -d "iso_contents" ] && [ -d "initrd" ]; then
    read -p "Delete iso_conents or initrd ? [Yn]: " yesno
    if [[ $yesno != "Y" ]]; then
      return
    fi

    sudo rm -rf iso_contents
    sudo rm -rf initrd
    echo "iso_contents and initrd are deleted"
  else
    echo "iso_contents or initrd not exist, try ISO extract first"
  fi
}

KERNELVERSION="6.1.2"


function ShowVars()
{
  echo
  echo "WORKINGDIR=$WORKINGDIR"
  echo "RELEASE=$RELEASE"
  echo "ISODIR=$ISODIR"
  echo "ISOSRC=$ISOSRC"
  echo "NEWISO=$NEWISO"
  echo "LINUX=$LINUX"
  echo
}

function MrProper()
{
  echo
  echo "Clean it all"
  cd $LINUXPATH
  make mrproper
  echo "Done"
}


function MakeModules()
{
  echo
  echo "Making modules using all cores"
  cd $LINUXPATH
  make modules -j`nproc`
  echo "Done"
}

function MakeKernel()
{
  echo
  echo "Making kernel bzImage using all cores"
  cd $LINUXPATH
  make bzImage -j`nproc`
  echo "Done"
}

function Reconfigure()
{
  echo
  echo "make menuconfig"
  cd $LINUXPATH
  make menuconfig
}

function MakeNoConfig()
{
  echo
  echo "make allnoconfig"
  cd $LINUXPATH
  make allnoconfig
  read -p "Change .config to SMP (Symmetrical Multi Processing) [Yn] ? " yesno
  if [[ $yesno == "Y" ]]; then
    sed -i 's/CONFIG_BROKEN_ON_SMP=y/# CONFIG_BROKEN_ON_SMP is not set/g' .config
    sed -i 's/# CONFIG_SMP is not set/CONFIG_SMP=y/g' .config
    echo "changed to SMP"
  fi
}

function LoadPackages()
{
  echo
  echo "Load all needed packages"
  tce-load -wi coreutils compiletc gcc binutils make squashfs-tools ncursesw-dev bison flex-dev openssl-1.1.1-dev elfutils-dev gettext-dev bc perl5
  echo "Done"
}

function ShowGLibCompat()
{
  strings /lib/libc.so.6 | grep GLIBC
}

function MakeNewGLib()
{
  tce-load -wi python3.9 texinfo
  cd $WORKINGDIR
  if [ ! -d "$GLIBVERSION" ]; then
    wget "https://ftp.gnu.org/gnu/glibc/$GLIBVERSION.tar.gz"
    echo "extracting sources ..."
    tar xzf "$GLIBVERSION.tar.gz"
    rm "$GLIBVERSION.tar.gz"
  fi
  cd "$GLIBVERSION"
  mkdir -p build
  mkdir -p install
  cd build
  echo "Configure ..."
  ../configure --prefix="$WORKINGDIR/$GLIBVERSION/install"
  make -j`nproc`
  make install
}


function InstallGLib()
{
  echo
  echo "install GLib"

  GLIB="$WORKINGDIR/$GLIBVERSION/install/lib"

  if [ ! -d $GLIB ]; then
    echo "installdir $GLIB does not exist"
    exit
  fi
  
  LIBDEST="$INITRD/lib"
  
  if [ ! -d $LIBDEST ]; then
    echo "lib destination $LIBDEST does not exist"
    exit
  fi

#  sudo find "$LIBDEST" -maxdepth 1 -type f -delete
#  sudo find "$LIBDEST" -maxdepth 1 -type l -delete

  FILES="$GLIB/*.so*"
  for f in $FILES
  do
    if [ ! -h "$f" ]
    then
      sudo strip $f 2>/dev/null
      if [ $? -eq 0 ]; then
        sudo cp -a $f $LIBDEST
      fi
    else
      sudo cp -a $f $LIBDEST
    fi
  done
  sudo chown -R root:root $LIBDEST
  echo "Done"
}

function SelectPreConfig()
{
  echo
  echo "Creating .config file for $LINUX"
  cd $SCRIPTDIR
  files=`ls -a Config*`
  i=1
  for file in $files; do
    echo "$i - $file"
    i="$(($i + 1))"
  done
  echo
  read -p "Select Config file to install q=quit ? " ccc
  if [ $ccc == "q" ]; then return ; fi

  i=1
  for file in $files; do
    if [[ $i == $ccc ]]; then
      echo
      echo "Copy $file to $LINUXPATH/.config"
      cp -f $file $LINUXPATH/.config
    fi
    i="$(($i + 1))"
  done
}


# ===========================================

echo

if [ "$(id -u)" -eq 0 ]; then echo "Please run as user (not root)."; exit 1; fi

if [ ! -d $WORKINGDIR ]; then echo "Directory $WORKINGDIR does not exist"; exit 1; fi

if [ ! -w $WORKINGDIR ]; then 
  sudo chown root:staff $WORKINGDIR
  sudo chmod 775 $WORKINGDIR
fi

if [ ! -d $ISODIR ]; then mkdir $ISODIR; fi

cd $ISODIR
if [ ! -f "$ISOSRC" ]; then
  read -p "Getting $ISOSRC From official Tinycore site ? [Yn]: " yesno
  if [[ $yesno == "Y" ]]; then
    wget "$REMOTE$ISOSRC"
    IsoExtract
  fi
fi

if [ ! -f "$ISODIR/$ISOSRC" ]; then echo "$ISOSRC can not be found in directory $ISODIR"; exit 1; fi

cd $WORKINGDIR

if [ ! -d "$LINUX" ]; then
  echo "LINUX directory for kernel $LINUX not found"

  read -p "Getting $LINUX From official kernel.org site ? [Yn]: " yesno
    if [[ $yesno != "Y" ]]; then
      exit
    fi
  wget "$LINSRC"
  echo "extracting sources ..."
  tar -xf $LINUX.tar.xz
  echo "removing tar file"
  rm $LINUX.tar.xz  
fi

cd $WORKINGDIR

ShowVars

while :
do
  echo
  echo "ISO-Builder $ISOBUILDER"
  echo "============================="
  echo "c - make mrproper"
  echo "0 - make allnoconfig (!!! better use your own .config file !!!)"
  echo "C - List and select predefined config files"
  echo "r - Re-configure using make menuconfig"
  echo "k - make bzImage (kernel)"
  echo "m - make modules"
  echo "i - Install Kernel and Modules"
  echo "n - Make new ISO"
  echo "p - Purge extraction"
  echo "x - ISO extract"
  echo "v - Show Variables"
  echo "w - install all packages for the build system"
  echo "s - Make ISO FS (modules64.gz, rootfs64.gz or corepure64.gz) and vmlinuz64"
  echo
  echo "q - Quit"
  echo
  read -p "c,0,r,k,m,i,n,p,x,v,w,s or q(uit) :" c
  case  $c  in
    c) MrProper ;;
    0) MakeNoConfig ;;
    C) SelectPreConfig ;;
    r) Reconfigure ;;
    k) MakeKernel ;;
    m) MakeModules ;;
    i) Install ;;
    n) MakeNewIso ;;
    p) PurgeExtraction ;;
    x) IsoExtract ;;
    v) ShowVars ;;
    w) LoadPackages ;;
    s) MakeISOFS ;;
    q) exit ;;
    *) echo "Say what? $c" ;;
  esac 
done
